CREATE DATABASE DBFILMS;
USE DBFILMS; 
CREATE TABLE ARTIST_TABLE1 
(
 ARTIST_ID int PRIMARY KEY,
ARTIST_NAME varchar(20),
ARTIST_GENDER varchar(20)
);
DESCRIBE ARTIST_TABLE1 ;

INSERT INTO ARTIST_TABLE1 VALUES(1,'SHARUK KHAN','MALE'),(2, 'KAJOL','FEMALE'),(3,'RANI MUKARJEE','FEMALE'),(4,'AJAY DEVGUN','MALE'),(6,'AMIR KHAN','MALE');
SELECT * FROM ARTIST_TABLE1 ;

CREATE TABLE MOVIE_DETAILS1
(
 MOVIE_TITLE varchar(20),
MOVIE_YEAR int,
MOVIE_RELEASE date,
DIRECTOR_FNAME varchar(20),
DIRECTOR_LNAME varchar(20),
PRODUCER_NAME varchar(20)
);
DESCRIBE MOVIE_DETAILS1;
INSERT INTO MOVIE_DETAILS1 VALUES('KUCH KUCH HOTA HEIN','2002','2002-02-20','KARAN','JOHAR','RAMKUMAR'),('DIL','1990','1990-04-08','INDRA','KUMAR','KAMLESH PANDEY'),('ISHQ','1997','1997-09-07','INDRA','KUMAR','GORDAHN TIWARI'),('MELA','2000','2000-02-20','DHARMESH','DHATAN','GANESH JAIN'),('LAJJA','2001','2001-03-21','RAJUKUMAR','SANTHOSHI','RAJKUMAR SANTHOSHI');
SELECT * FROM  MOVIE_DETAILS1;

CREATE TABLE REVIEW_TABLE2
(
STARS int,
FILM_ID int

);
DESCRIBE REVIEW_TABLE1;
INSERT INTO REVIEW_TABLE1 VALUES('10','5'),('11','3'),('12','2'),('13','1'),(14,'5'),('15','3');
SELECT * FROM REVIEW_TABLE;

CREATE TABLE CASTING_ID4
(
ARTIST_ID int PRIMARY KEY,
FILM_ID int,
MOVIE_YEAR int
);
SELECT *FROM CASTING_ID4;

INSERT INTO CASTING_ID4 VALUES('1','101','2002'),('2','111','1990'),('3','121','1997'),('4','131','2000'),('5','141','2001');
SELECT * FROM CASTING_ID4;

CREATE TABLE MOVIE_DATA
(
MOVIE_TITLE  varchar(20),
ARTIST_NAME varchar(20),
STARS  int
);
insert into MOVIE_DATA VALUES('KUCH KUCH HOTA HEIN','SHARUK KHAN','5'),('DIL','KAJOL','3'),('ISHQ',' RANI MUKARJEE','2') ,('MELA','AJAY','1'),('LAJJA','AMIR KHAN','3');

CREATE TABLE PRODUCER_DATA4
(
ARTIST_ID int ,
PRODUCER_NAME varchar(20),
FILMSUCCESS_ID int PRIMARY KEY,
MOVIE_YEAR int
);
insert into PRODUCER_DATA4 VALUES('1','RAMKUMAR','101','2002'),('2','KAMLESH PANDEY','111','1990'),('3','GORDAHN TIWARI','121','1997'),('4','GANESH JAIN','141','2000'),('5','RAJKUMAR SANTHOSHI','151','2001');
SELECT * FROM PRODUCER_DATA4;

CREATE TABLE MOVIE_BASE
(
MOVIE_BASE varchar(20),
MOVIE_RESULT varchar(20),
ACTOR_ID int PRIMARY KEY,
FOREIGN KEY(FILMSUCCESS_ID)
REFERENCES PRODUCER_DATA4(FILMSUCCESS_ID)
);

SELECT MOVIE_YEAR,FILM_ID FROM CASTING_ID4
GROUP BY ARTIST_ID
HAVING ARTIST_ID='4';

SELECT * FROM MOVIE_DETAILS1 WHERE MOVIE_YEAR='2002';

SELECT ARTIST_ID,FILM_ID FROM CASTING_ID01 WHERE MOVIE_YEAR='2000';

SELECT MOVIE_TITLE,MOVIE_YEAR,MOVIE_RELEASE,PRODUCER_NAME FROM MOVIE_DETAILS1 WHERE DIRECTOR_LNAME='KUMAR';

SELECT * FROM ARTIST_TABLE WHERE ARTIST_NAME='KAJOL';

SELECT * FROM MOVIE_DETAILS1 WHERE MOVIE_TITLE='ISHQ' AND  DIRECTOR_LNAME='KUMAR';

SELECT * FROM CASTING_ID4 INNER JOIN ARTIST_TABLE1
ON CASTING_ID4.FILM_ID = ARTIST_TABLE1.ARTIST_ID;

SELECT *
FROM MOVIE_DETAILS1
GROUP BY MOVIE_TITLE='MELA';

SELECT MOVIE_TITLE FROM 
MOVIE_DETAILS1 WHERE 
MOVIE_YEAR='2000';

SELECT *FROM 
MOVIE_DETAILS1 WHERE 
MOVIE_YEAR='1990';


SELECT CASTING_ID4.FILM_ID,
CASTING_ID4.ARTIST_ID,CASTING_ID4.MOVIE_YEAR
FROM
CASTING_ID4 RIGHT OUTER JOIN PRODUCER_DATA4
ON  CASTING_ID4.ARTIST_ID=PRODUCER_DATA4.ARTIST_ID;

SELECT CASTING_ID4.FILM_ID,
CASTING_ID4.ARTIST_ID,CASTING_ID4.MOVIE_YEAR
FROM
CASTING_ID4 LEFT OUTER JOIN PRODUCER_DATA4
ON  CASTING_ID4.ARTIST_ID=PRODUCER_DATA4.ARTIST_ID;